spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: hello
          uri: http://localhost:8002/hello
          predicates:
            - Path=/hello
server:
  port: 13001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

#logging:
#  level:
#    org.springframework.cloud.gateway: debug