server:
  port: 13001

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: hello
          uri: lb://provider
          predicates:
            - Path=/hello/**
          filters:
            - name: Retry # 重试
              args:
                retries: 3 # retries：重试次数，默认值是 3 次
                statuses: INTERNAL_SERVER_ERROR # HTTP 的状态返回码，取值请参考：org.springframework.http.HttpStatus
                methods: GET,POST # 指定哪些方法的请求需要进行重试逻辑，默认值是 GET 方法，取值参考：org.springframework.http.HttpMethod
                series: SERVER_ERROR # 一些列的状态码配置，取值参考：org.springframework.http.HttpStatus.Series。符合的某段状态码才会进行重试逻辑，默认值是 SERVER_ERROR，值是 5，也就是 5XX(5 开头的状态码)，共有5 个值
            - name: Hystrix # 熔断
              args:
                name: fallbackcmd
                fallbackUri: forward:/defaultFallback # 服务降级地址
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Retry
              args:
                retries: 3 # retries：重试次数，默认值是 3 次
                statuses: BAD_GATEWAY # HTTP 的状态返回码，取值请参考：org.springframework.http.HttpStatus
                methods: GET,POST # 指定哪些方法的请求需要进行重试逻辑，默认值是 GET 方法，取值参考：org.springframework.http.HttpMethod
#                series: SERVER_ERROR # 一些列的状态码配置，取值参考：org.springframework.http.HttpStatus.Series。符合的某段状态码才会进行重试逻辑，默认值是 SERVER_ERROR，值是 5，也就是 5XX(5 开头的状态码)，共有5 个值
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug

jwt:
  test: hello/login, hello/login2, /auth/token
  token:
    expireTime: 1800 # 秒
  ignoreUrlList:
    - "hello/login"
    - "hello/login2"