spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: hello
          uri: lb://provider
          predicates:
            - Path=/hello/**
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
server:
  port: 13001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug

jwt:
  test: hello/login, hello/login2, /auth/token
  token:
    expireTime: 1800 # √Î
  ignoreUrlList:
    - "hello/login"
    - "hello/login2"