spring:
  application:
    name: consumer
server:
  port: 15001
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #这里有坑，default-zone->defaultZone
feign:
  hystrix:
    enabled: true
    #替换掉JDK默认HttpURLConnection实现的 Http Client
  httpclient:
    enabled: true
  client:
    config:
      default:
        #连接超时时间
        connectTimeout: 5000
        #读取超时时间
        readTimeout: 5000