spring:
  application:
    name: consumer
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #这里有坑，default-zone->defaultZone
feign:
  hystrix:
    enabled: true