#server:
#  port: 7001
#
#eureka:
#  instance:
#    hostname: eureka7001.com #eureka服务端的实例名称(这里使用了虚拟主机映射，修改hosts文件即可实现)
#  client:
#    register-with-eureka: false     #false表示不向注册中心注册自己。
#    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
#    service-url:
#      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---
spring:
  application:
    name: eureka-discovery-7001
  profiles: eureka7001
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false
    fetch-registry: false
---
spring:
  application:
    name: eureka-discovery-7002
  profiles: eureka7002
server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false
    fetch-registry: false
---
spring:
  application:
    name: eureka-discovery-7003
  profiles: eureka7003
server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003.com
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
    register-with-eureka: false
    fetch-registry: false
