server:
  port: 10001
spring:
  application:
    name: spring-cloud-config-server
#  profiles:
#    active:
#    - native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ityouknow/spring-cloud-starter/     # 配置git仓库的地址
          search-paths: config-repo                                   # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                                   # git仓库的账号
          password:                                                   # git仓库的密码