server:
  port: 8601
spring:
  application:
    name: spring-cloud-consul-consumber
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # 注册到consul的服务名称
        serviceName: consul-consumber
        enabled: true
      enabled: true
#      discovery:
#        # 启用服务发现
#        enabled: true
#        # 启用服务注册
#        register: true
#        # 服务停止时取消注册
#        deregister: true
#        # 表示注册时使用IP而不是hostname
#        prefer-ip-address: true
#        # 执行监控检查的频率
#        health-check-interval: 30s
#        # 设置健康检查失败多长时间后，取消注册
#        health-check-critical-timeout: 30s
#        # 健康检查的路径
#        health-check-path: /actuator/info
#        # 服务注册标识，格式为：应用名称+服务器IP+端口
#        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
